export type CaseStudy = {
  slug: string;
  area: string;
  title: string;
  summary: string;
  overview: string;
  built: string;
  delivered: string;
  tech: string[];
  githubUrl?: string;
  projectUrl?: string;
  thumbnail?: string;
  thumbnailFit?: "cover" | "contain";
  fullTextPath?: string;
};

export const caseStudies: CaseStudy[] = [
  {
    slug: "lap-credit-risk-intelligence",
    area: "Loan Against Property · Credit AI",
    title: "LAP Credit Risk Intelligence",
    summary: "A Python-based underwriting system combining bank-statement intelligence, policy rules, XGBoost risk prediction, SHAP explainability, and LLM-generated decision reasoning.",
    overview: "An end-to-end Loan Against Property decisioning workflow designed to turn financial documents and structured loan applications into traceable credit insights, eligibility decisions, and pricing recommendations.",
    built: "Designed the Python data-processing and AI workflow across OCR extraction, transaction classification, hidden-EMI detection, feature engineering, knockout rules, XGBoost inference, SHAP analysis, and LLM explanations.",
    delivered: "Connected deterministic policy checks with machine-learning risk assessment and generative-AI explanations, producing structured outputs with risk drivers, rejection reasons, audit data, and pricing signals.",
    tech: ["Python", "pandas", "XGBoost", "SHAP", "OpenAI", "OCR", "PostgreSQL", "Docker"],
    fullTextPath: "lap-credit-risk-case-study.txt",
  },
  {
    slug: "margin-intelligence",
    area: "Insurance AI",
    title: "Margin Intelligence",
    summary: "AI intelligence layer combining machine learning, document analysis, workflow automation, and explainable human review.",
    overview: "An AI-powered platform supporting complex insurance operations through machine learning, document intelligence, and workflow automation.",
    built: "Owned the AI/ML layer, including model development, Langflow orchestration, document intelligence, and Python API integration.",
    delivered: "Connected trained models, OCR, anomaly and tampering indicators, explainable outputs, and auditable results in a deployment-ready system.",
    tech: ["Python", "Langflow", "Machine Learning", "Generative AI", "OCR", "PostgreSQL"],
    thumbnail: "/margin-intelligence-conference.png",
    fullTextPath: "margin-intelligence-case-study.txt",
  },
  {
    slug: "qurio",
    area: "AI Learning Platform · Work in progress",
    title: "Qurio",
    summary: "A learn-by-doing AI education platform with guided courses, interactive practice, and an AI learning companion.",
    overview: "A Next.js learning platform for AI, RAG systems, and modern engineering, organised into phase-by-phase courses with progress tracking and gamification.",
    built: "Built the course catalogue, roadmap and phase views, interactive assignments, quizzes, learner profile, progress dashboard, and AI mascot experience.",
    delivered: "Implemented Clerk authentication, Supabase-backed progress and gamification sync, and Anthropic-powered learning guidance. The product is still actively being developed.",
    tech: ["Next.js", "React", "TypeScript", "Clerk", "Supabase", "Anthropic"],
    projectUrl: "https://theqrio.com/",
    thumbnail: "/qurio-mascot.png",
    thumbnailFit: "contain",
  },
  {
    slug: "rag-criminal-defense-research",
    area: "RAG",
    title: "RAG Criminal Defense Research",
    summary: "Private, locally hosted RAG system for law firms to query criminal defense research material.",
    overview: "A privacy-first research assistant for retrieving relevant legal material and answering questions over a private document collection.",
    built: "Document retrieval flow, local LLM integration, and research-focused question answering over legal material.",
    delivered: "Used a private stack so sensitive research workflows could run without sending documents to hosted model APIs.",
    tech: ["RAG", "LangChain", "Ollama", "Docker"],
    githubUrl: "https://github.com/Nehainit/RAG_criminal-defense-research",
  },
  {
    slug: "automated-report-generator",
    area: "BI Automation",
    title: "Automated Report Generator",
    summary: "LLM-powered business intelligence reporting across multiple data sources.",
    overview: "A reporting pipeline that combines data processing with language-model summaries for readable business updates.",
    built: "Data ingestion flow, AI-generated written summaries, and report assembly for business analysis.",
    delivered: "Connected data processing with language-model reporting so raw metrics could become readable business updates.",
    tech: ["LangChain", "FastAPI", "Multi-source"],
    githubUrl: "https://github.com/Nehainit/automated-report-generator",
  },
  {
    slug: "ai-powered-ats",
    area: "AI Agents",
    title: "AI-Powered ATS",
    summary: "Applicant tracking workflow with AI-assisted candidate screening and match scoring.",
    overview: "An applicant tracking workflow that helps compare candidates against role requirements and surface stronger matches.",
    built: "Candidate parsing, AI scoring, and an application workflow for comparing applicants against role needs.",
    delivered: "Combined Python and TypeScript pieces to make resume evaluation easier to inspect and act on.",
    tech: ["AI Agents", "Python", "TypeScript"],
    githubUrl: "https://github.com/Nehainit/AI-powered-ATS",
  },
  {
    slug: "voice-agent",
    area: "Voice AI",
    title: "CodeDuck Voice Agent",
    summary: "Local-first desktop voice coding agent for speaking requests to a coding assistant.",
    overview: "An always-on-top Electron companion that captures spoken coding requests and connects them to a private local AI service.",
    built: "Voice capture, highlighted-code context, local model orchestration, answer streaming, and patch previews for code changes.",
    delivered: "Kept sensitive coding workflows local with Electron, FastAPI, Ollama, speech-to-text, and approval-based patch application.",
    tech: ["Electron", "FastAPI", "Ollama", "Whisper", "LangChain"],
    githubUrl: "https://github.com/Nehainit/Voice_Agent",
  },
  {
    slug: "ocr-comparison",
    area: "Document AI",
    title: "OCR Comparison",
    summary: "OCR comparison project for evaluating document text extraction approaches.",
    overview: "A document-AI project focused on comparing OCR outputs and extraction quality across different approaches.",
    built: "OCR processing and comparison workflows for turning document images into text that can be reviewed and evaluated.",
    delivered: "Made OCR quality differences easier to inspect when selecting an extraction approach for document workflows.",
    tech: ["OCR", "Python", "Document AI"],
    githubUrl: "https://github.com/Nehainit/OCR_comparision",
  },
  {
    slug: "ai-powered-etl-pipeline",
    area: "ETL",
    title: "AI-Powered ETL Pipeline",
    summary: "LLM-driven ETL pipeline for automatic schema detection and mapping.",
    overview: "An API-backed data pipeline that uses an LLM to interpret source columns and assist with transformation mapping.",
    built: "Automated schema detection, mapping assistance, and API-backed ETL flow for moving structured data.",
    delivered: "Reduced manual mapping effort by using the model where column meaning and transformation intent needed interpretation.",
    tech: ["LLM", "ETL", "FastAPI", "Claude"],
    githubUrl: "https://github.com/Nehainit/AI-ETL-PIPELINE",
  },
  {
    slug: "real-time-data-quality-monitor",
    area: "Data Quality",
    title: "Real-Time Data Quality Monitor",
    summary: "AI-powered anomaly detection and root cause analysis for streaming data quality monitoring.",
    overview: "A monitoring workflow for tracking streaming-data completeness, accuracy, anomalies, and likely root causes.",
    built: "Streaming quality checks, anomaly signals, and dashboard views for monitoring completeness and accuracy.",
    delivered: "Paired data-quality metrics with AI-assisted root cause notes so issues were easier to investigate.",
    tech: ["Kafka", "Streamlit", "Claude API"],
    githubUrl: "https://github.com/Nehainit/data-quality-monitor",
  },
  {
    slug: "bank-statement-extractor",
    area: "Document AI",
    title: "Bank Statement Extractor",
    summary: "AI document extraction workflow for parsing bank statements into structured transaction data.",
    overview: "A document-processing workflow that turns uploaded bank statements into transaction-ready structured data.",
    built: "PDF upload flow, OCR extraction, AI-assisted field parsing, and transaction-ready structured output.",
    delivered: "Turned unstructured bank statement documents into cleaner data for downstream review and analysis.",
    tech: ["Claude API", "OCR", "Streamlit"],
    githubUrl: "https://github.com/Nehainit/bank-statment-extractor",
  },
  {
    slug: "cash-flow-intelligence",
    area: "Langflow",
    title: "Cash Flow Intelligence",
    summary: "Financial analysis workflow built with Langflow for cash-flow-oriented intelligence.",
    overview: "A visible, finance-oriented LLM workflow for turning cash-flow inputs into structured analysis.",
    built: "Input-to-LLM workflow steps for finance-oriented analysis and structured output generation.",
    delivered: "Used Langflow to keep the financial reasoning workflow visible and easier to iterate.",
    tech: ["Langflow", "LLM", "Finance"],
    githubUrl: "https://github.com/Nehainit",
  },
  {
    slug: "credit-risk-assessment",
    area: "Langflow",
    title: "Credit Risk Assessment",
    summary: "AI-driven credit risk scoring workflow for assessing borrower risk signals.",
    overview: "A workflow that makes credit-risk reasoning easier to inspect by presenting its analysis as visible steps.",
    built: "Risk-analysis workflow blocks, LLM-assisted assessment steps, and score-oriented output.",
    delivered: "Created a workflow that made credit risk reasoning easier to inspect instead of hiding it behind a black box.",
    tech: ["Langflow", "Risk Analysis", "AI"],
    githubUrl: "https://github.com/Nehainit",
  },
];
